apiVersion: v2
name: sumologic
version: 2.18.1
appVersion: 2.18.1
description: A Helm chart for collecting Kubernetes logs, metrics, traces and events into Sumo Logic.
type: application
keywords:
  - monitoring
  - logging
icon: https://raw.githubusercontent.com/SumoLogic/sumologic-kubernetes-collection/main/images/sumo_logic_logo.png
home: https://github.com/SumoLogic/sumologic-kubernetes-collection
sources:
  - https://github.com/SumoLogic/sumologic-kubernetes-collection
dependencies:
  - name: sumologic
    version: 2.18.1
    repository: https://sumologic.github.io/sumologic-kubernetes-collection
